# Generated by Django 3.0.8 on 2020-10-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200508_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='picture',
            new_name='image',
        ),
    ]
